//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Update.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Update.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a backup of the data file &apos;{0}&apos; as &apos;{1}&apos;..
        /// </summary>
        public static string Action_BackupData {
            get {
                return ResourceManager.GetString("Action_BackupData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup of data before updating..
        /// </summary>
        public static string Action_BackupDataBeforeUpdate {
            get {
                return ResourceManager.GetString("Action_BackupDataBeforeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder: .
        /// </summary>
        public static string Action_BackupFolder {
            get {
                return ResourceManager.GetString("Action_BackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the target folder &apos;{0}&apos; for data backup before update..
        /// </summary>
        public static string Action_BackupFolderError {
            get {
                return ResourceManager.GetString("Action_BackupFolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a backup of the schema file &apos;{0}&apos; as &apos;{1}&apos;..
        /// </summary>
        public static string Action_BackupSchema {
            get {
                return ResourceManager.GetString("Action_BackupSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup schema before updating..
        /// </summary>
        public static string Action_BackupSchemaBeforeUpdate {
            get {
                return ResourceManager.GetString("Action_BackupSchemaBeforeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the &apos;{0}&apos; item in the &apos;{1}&apos; configuration file..
        /// </summary>
        public static string Action_ConfigFileElementError {
            get {
                return ResourceManager.GetString("Action_ConfigFileElementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation of the backup copy &apos;{0}&apos; of the file &apos;{1}&apos; has failed..
        /// </summary>
        public static string Action_CopyFileError {
            get {
                return ResourceManager.GetString("Action_CopyFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the data backup folder &apos;{0}&apos;..
        /// </summary>
        public static string Action_CreateBackupFolder {
            get {
                return ResourceManager.GetString("Action_CreateBackupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML data file: {0}.
        /// </summary>
        public static string Action_DataFilePath {
            get {
                return ResourceManager.GetString("Action_DataFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all files used for the update..
        /// </summary>
        public static string Action_DeleteUdpateFiles {
            get {
                return ResourceManager.GetString("Action_DeleteUdpateFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message: {0}.
        /// </summary>
        public static string Action_ErrorCode {
            get {
                return ResourceManager.GetString("Action_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string Action_File {
            get {
                return ResourceManager.GetString("Action_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the data file &apos;{0}&apos;..
        /// </summary>
        public static string Action_FileNotFound {
            get {
                return ResourceManager.GetString("Action_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract the path to the data file from exe.config file..
        /// </summary>
        public static string Action_GetDataPath {
            get {
                return ResourceManager.GetString("Action_GetDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract the path to the schema file from data file..
        /// </summary>
        public static string Action_GetSchemaPath {
            get {
                return ResourceManager.GetString("Action_GetSchemaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the new XSD schema is not defined in the update parameter file..
        /// </summary>
        public static string Action_NewSchemaNameNotFound {
            get {
                return ResourceManager.GetString("Action_NewSchemaNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the file &apos;{0}&apos; with its new version..
        /// </summary>
        public static string Action_ReplaceFile {
            get {
                return ResourceManager.GetString("Action_ReplaceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while replacing the file &apos;{0}&apos;. .
        /// </summary>
        public static string Action_ReplaceFileError {
            get {
                return ResourceManager.GetString("Action_ReplaceFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the data schema..
        /// </summary>
        public static string Action_ReplaceSchema {
            get {
                return ResourceManager.GetString("Action_ReplaceSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the XSD data schema file &apos;{0}&apos; with the new version..
        /// </summary>
        public static string Action_ReplaceSchemaFile {
            get {
                return ResourceManager.GetString("Action_ReplaceSchemaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can restart SeatFlow..
        /// </summary>
        public static string Action_RestartSeatFlow {
            get {
                return ResourceManager.GetString("Action_RestartSeatFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSD schema file from XML data: {0}.
        /// </summary>
        public static string Action_SchemaFilePath {
            get {
                return ResourceManager.GetString("Action_SchemaFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update is aborted!.
        /// </summary>
        public static string Action_UpdateAborted {
            get {
                return ResourceManager.GetString("Action_UpdateAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating data..
        /// </summary>
        public static string Action_UpdateData {
            get {
                return ResourceManager.GetString("Action_UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successfully completed..
        /// </summary>
        public static string Action_UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("Action_UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating &apos;{0}&apos; elements..
        /// </summary>
        public static string Action_UpdateElement {
            get {
                return ResourceManager.GetString("Action_UpdateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the installation of the update from version &apos;{0}&apos; to version &apos;{1}&apos;..
        /// </summary>
        public static string Action_UpdateStarted {
            get {
                return ResourceManager.GetString("Action_UpdateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the &apos;{0}&apos; item in the &apos;{1}&apos; XML file..
        /// </summary>
        public static string Action_XMLElementError {
            get {
                return ResourceManager.GetString("Action_XMLElementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An XML error occurred while reading the file &apos;{0}&apos;..
        /// </summary>
        public static string Action_XmlError {
            get {
                return ResourceManager.GetString("Action_XmlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string Button_Quit {
            get {
                return ResourceManager.GetString("Button_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Update.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Column_Action {
            get {
                return ResourceManager.GetString("Column_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SeatFlow application is not installed in the &apos;{0}&apos; folder..
        /// </summary>
        public static string Info_AppNotFound {
            get {
                return ResourceManager.GetString("Info_AppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;{0}&apos; to install SeatFlow version {1}..
        /// </summary>
        public static string Info_BeforeUpdate {
            get {
                return ResourceManager.GetString("Info_BeforeUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact support..
        /// </summary>
        public static string Info_ContactSupport {
            get {
                return ResourceManager.GetString("Info_ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message:.
        /// </summary>
        public static string Info_Exception {
            get {
                return ResourceManager.GetString("Info_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can restart SeatFlow..
        /// </summary>
        public static string Info_RestartSeatFlow {
            get {
                return ResourceManager.GetString("Info_RestartSeatFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update did not successfully complete..
        /// </summary>
        public static string Info_UpdateAborted {
            get {
                return ResourceManager.GetString("Info_UpdateAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update cannot be performed !.
        /// </summary>
        public static string Info_UpdateCannotBePerformed {
            get {
                return ResourceManager.GetString("Info_UpdateCannotBePerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version &apos;{0}&apos; of SeatFlow has been successfully installed..
        /// </summary>
        public static string Info_UpdateEndedSuccessfully {
            get {
                return ResourceManager.GetString("Info_UpdateEndedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current SeatFlow release &apos;{0}&apos; does not match the updatable release &apos;{1}&apos;..
        /// </summary>
        public static string Info_WrongVersion {
            get {
                return ResourceManager.GetString("Info_WrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML File:.
        /// </summary>
        public static string Info_XMLFilePath {
            get {
                return ResourceManager.GetString("Info_XMLFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML file containing the parameters of the operations to be performed during the update is not available. .
        /// </summary>
        public static string Info_XMLFileUnavailable {
            get {
                return ResourceManager.GetString("Info_XMLFileUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while reading the XML file containing the parameters of the operations to be performed during the update..
        /// </summary>
        public static string Info_XMLParse {
            get {
                return ResourceManager.GetString("Info_XMLParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string MandatoryField {
            get {
                return ResourceManager.GetString("MandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ToolTip_Close {
            get {
                return ResourceManager.GetString("ToolTip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory field.
        /// </summary>
        public static string ToolTip_MandatoryField {
            get {
                return ResourceManager.GetString("ToolTip_MandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ViewTitle_Update {
            get {
                return ResourceManager.GetString("ViewTitle_Update", resourceCulture);
            }
        }
    }
}
